backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "date" }
      - { label: "Authors", name: "authors", widget: "list", default: []}
      - { label: "Description", name: "description", widget: "string"}
      - { label: "Featured Image", name: "image", widget: "image", required: false}
      - { label: "Tags", name: "tags", widget: "list", default: ["news"]}
      - { label: "Categories", name: "categories", widget: "list", default: ["Klezmer"]}
      - { label: "Body", name: "body", widget: "markdown" }
